### PR TITLE
Add a live dev server

### PR DESCRIPTION
**Pull request by maxmechanic**
Separated some code to make some browser-friendly functions, so we can play with output in the browser! 

`npm run dev` will start budo, building `dev.js`, and `npm run grid` will generate and open a grid png. 

Added a readme gif, too ~~~~
(EDIT: fast-changing gif removed)

### CODE REVIEW

**Comment by beaugunderson** [comment]
this is great! rather than the gif i'm gonna use a grid though; just in case anyone who [suffers from motion sickness](http://tarnoff.info/blog/granting-the-user-control/) wants to contribute

p.s. i love `budo`, such a useful tool

**Comment by beaugunderson** [comment]
p.p.s. 😻😻😻😻😻

**Comment by maxmechanic** [comment]
Ahhh, didn't think about the switch rate :sweat:, I was just excited about a cat parade.

**Comment by beaugunderson** [comment]
no worries! i love the cat parade, i had it in the original codepen i made in april :) i wouldn't know about #dzy except for having attended OS & Feels last year, but i wanted to make this project Maximally Inclusive :sparkles:

**Comment by beaugunderson** [comment]
there were some conflicts because I had been making some similar changes; so despite GitHub saying this hasn't been merged it actually has, thank you! :sparkles:

**Pull request closed without merging**
