### PR TITLE
Tabby forehead markings

### PR DESCRIPTION
**Pull request by araile**
Adds a head-marking variety for some tabby stripes on the forehead. :3

### CODE REVIEW

**Comment by araile** [comment]
output

**Comment by beaugunderson** [comment]
AHHHHHH 😻😻😻😻😻😻😻

**Comment by beaugunderson** [comment]
i pushed my change that makes all drawing start from centerX, centerY too which makes the drawing code easier to read & write :)

**Comment by araile** [comment]
ooh this looks much neater!

**Pull request merged**
